/** @type {import('tailwindcss').Config} */

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("./src/plugin.cjs")],
  darkMode: "class",
  // for dynamic content
  safelist: [
    "animate-[fade-in_1s_ease-in-out]",
    "animate-[fade-in-down_1s_ease-in-out]",
    "animate-[fade-in-left_1s_ease-in-out]",
    "animate-[fade-in-right_1s_ease-in-out]",
    "animate-[fade-in-up_1s_ease-in-out]",
    "animate-[fade-out_1s_ease-in-out]",
    "animate-[fade-out-down_1s_ease-in-out]",
    "animate-[fade-out-left_1s_ease-in-out]",
    "animate-[fade-out-right_1s_ease-in-out]",
    "animate-[fade-out-up_1s_ease-in-out]",
    "animate-[slide-in-down_1s_ease-in-out]",
    "animate-[slide-in-left_1s_ease-in-out]",
    "animate-[slide-in-right_1s_ease-in-out]",
    "animate-[slide-in-up_1s_ease-in-out]",
    "animate-[slide-out-down_1s_ease-in-out]",
    "animate-[slide-out-left_1s_ease-in-out]",
    "animate-[slide-out-right_1s_ease-in-out]",
    "animate-[slide-out-up_1s_ease-in-out]",
    "animate-[slide-down_1s_ease-in-out]",
    "animate-[slide-left_1s_ease-in-out]",
    "animate-[slide-right_1s_ease-in-out]",
    "animate-[slide-up_1s_ease-in-out]",
    "animate-[zoom-in_1s_ease-in-out]",
    "animate-[zoom-out_1s_ease-in-out]",
    "animate-[tada_1s_ease-in-out]",
    "animate-[spinner-grow_1s_ease-in-out]",
    "animate-[drop-in_0.5s]",
    "animate-[drop-out_0.5s]",
    "animate-[fly-in_0.5s]",
    "animate-[fly-in-up_0.5s]",
    "animate-[fly-in-down_0.5s]",
    "animate-[fly-in-left_0.5s]",
    "animate-[fly-in-right_0.5s]",
    "animate-[fly-out_0.5s]",
    "animate-[fly-out-up_0.5s]",
    "animate-[fly-out-down_0.5s]",
    "animate-[fly-out-left_0.5s]",
    "animate-[fly-out-right_0.5s]",
    "animate-[browse-in_0.5s]",
    "animate-[browse-out_0.5s]",
    "animate-[browse-out-left_0.5s]",
    "animate-[browse-out-right_0.5s]",
    "animate-[jiggle_0.5s]",
    "animate-[flash_0.7s]",
    "animate-[shake_0.5s]",
    "animate-[glow_0.5s]",
  ],
};
